import './globals.css';
import type { Metadata } from 'next';
import { Roboto, Dela_Gothic_One } from 'next/font/google';

export const delaGothicOne = Dela_Gothic_One({ subsets: ['latin'], weight: ['400'] });
export const roboto = Roboto({ subsets: ['latin'], weight: ['400', '100', '300', '900', '700', '500'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
